version: "3.8"
services:
  honeypot:
    build: ./
    hostname: "honeypot"
    networks:
      - honeypot
    ports:
      - "80:8080"
    volumes:
      - logs:/var/log/apache2/
      - $PWD/httpd.conf:/usr/local/apache2/conf/httpd.conf

  auditbeat:
    image: docker.elastic.co/beats/auditbeat:7.15.0
    hostname: "auditbeat"
    user: root
    pid: host
    cap_add:
      - AUDIT_CONTROL
      - AUDIT_READ
    networks:
      - honeypot
    volumes:
      - auditbeat:/usr/share/auditbeat/data
      - $PWD/auditbeat.yml:/usr/share/auditbeat/auditbeat.yml:ro
    environment:
      - ELASTICSEARCH_HOST=192.168.1.2 # Change
      - KIBANA_HOST=192.168.1.2 # Change
      - ELASTICSEARCH_USERNAME=elastic # Change
      - ELASTICSEARCH_PASSWORD=changeme # Change
    command: ["--strict.perms=false"]
    depends_on:
      - honeypot

  filebeat:
    image: docker.elastic.co/beats/filebeat:7.15.0
    hostname: "filebeat"
    user: root
    networks:
      - honeypot
    volumes:
      - filebeat:/usr/share/filebeat/data
      - $PWD/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - $PWD/apache.yml:/usr/share/filebeat/modules.d/apache.yml
      - logs:/log/:ro
    environment:
      - ELASTICSEARCH_HOST=192.168.1.2 # Change
      - KIBANA_HOST=192.168.1.2 # Change
      - ELASTICSEARCH_USERNAME=elastic # Change
      - ELASTICSEARCH_PASSWORD=changeme # Change
    command: ["--strict.perms=false"]
    depends_on:
      - honeypot

networks:
  honeypot:

volumes:
  auditbeat:
  filebeat:
  logs: